cargo-features = ["edition2021"]

[package]
name = "gpgrt-src"
version = "142.0.0+1.42"
edition = "2021"

[dependencies]
ffi-tools = { version = "0.1", git = "https://github.com/byhowe/ffi-tools-rs.git" }
